### ISSUE TITLE
Fixing live website thread card stack overlap & theme switch (fix+enhancement)

### ISSUE THREAD

**Issue by IndigoWizard** [House-of-M/contributors-wall#28]
## Live website issues
- The theme switch button is doubled and not styled.
- The contribution thread is messedup at the bottom with overlapping card stacks. 

## preview
|repetitive check box div| over stacked usercards|
|--|--|
|![image](https://user-images.githubusercontent.com/43890965/139565727-404278d1-d470-442f-9ed9-da7e898a4bed.png)|![image](https://user-images.githubusercontent.com/43890965/139565807-963c71e1-43cd-4734-9eec-e4a3e427be7e.png)|

### repetitive check box div
Based on the commit and merge history the first issue (checkbox glitch) emerged in commit 696ab7f50ab1166e011a3b0e2e50255dbe840f00 during a hotfix from @L4RBI that was meant to fix the issue...

### over stacked usercards
Issue happened after contribution 1dca8cc336ed1bbfdaac3574b47c62580115355b was merged in PR #23 97a6483a1df28b08158eec1a41089a5ec7f9b475 which didn't align with the right contribution steps during which contributors add their code at the top of the thread and not at the bottom to avoid conflicts.

## Fix
- The theme switch box will be reworked, keeping the base functionality but moving the button in the nav bar + styling the switch button.
- Restacking the thread based on PR chronological order and stacking latest contributions from top to bottom.
- All upcoming contributions must be at the top of the thread.

**Comment by thatjohanntrent-2-googlegroups-com** [comment]
![favicon](https://github.com/House-of-M/contributors-wall/assets/165110785/23550bf0-d9b7-40b2-82a9-25e33833bcf0)
what there a k
