### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by IndigoWizard** [House-of-M/contributors-wall#4]
# Info
So far the live website of the repo has only one light theme. It would be great to have a dark theme switch as well.

## How
- Feel free to to use either CSS or JavaScript (vanilla preferably) to build a theme switch.
- In the CSS **:root** element you'll find an already setup color palette, use them to build the color palette for dark theme mode (feel free to add some colors if needed).
- The main logo SVGs are available in two colors; white & red. use what suits the theme for better visibility.

## PR
- Please explain what method you used and how you built the feature (briefly).
- Make sure to include some screenshots for the results in your Pull Request submission (you can put them in a markdown table if you're doing a comparison if you wish).

### Notes:
- Keep css variable naming convention as setup in the style sheet.
- If you are opting for JS, please mind to create a folder dedicated for scripts inside src folder as *./src/scripts*.

**Comment by IndigoWizard** [comment]
@pavan-nambi yup, you're up!

**Comment by pavan-nambi** [comment]
i did as per users system mode lmk if its not the case

**Comment by pavan-nambi** [comment]
ok

**Comment by pavan-nambi** [comment]
ignore first commit as it was based on system os mode in second commit its changing imo idk why you added main tag

**Comment by IndigoWizard** [comment]
@pavan-nambi alright i'll give it a quick check

**Comment by pavan-nambi** [comment]
ok

**Comment by Mihir008** [comment]
Hello sir, could you please assign me this???

**Comment by IndigoWizard** [comment]
This issue has been resolved with the merging of the Pull Request #6 and closes it.
